// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Gixanp9Kf7k_T0o6HyESchnew7Nxqjs',
    appId: '1:861560885487:web:2c913dcb83f2551da64b1a',
    messagingSenderId: '861560885487',
    projectId: 'letmecook-864e0',
    authDomain: 'letmecook-864e0.firebaseapp.com',
    storageBucket: 'letmecook-864e0.appspot.com',
    measurementId: 'G-WPWVPLV32W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRUh-jzSCD3wyLIN5_n2m4f76wqiey2NM',
    appId: '1:861560885487:android:ecd7b29b31d7cb13a64b1a',
    messagingSenderId: '861560885487',
    projectId: 'letmecook-864e0',
    storageBucket: 'letmecook-864e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWAQDgCU5jTkqEtjqSECZDs9Qun4BrDq8',
    appId: '1:861560885487:ios:c0e6b1ef7f917012a64b1a',
    messagingSenderId: '861560885487',
    projectId: 'letmecook-864e0',
    storageBucket: 'letmecook-864e0.appspot.com',
    iosBundleId: 'com.example.letmecook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWAQDgCU5jTkqEtjqSECZDs9Qun4BrDq8',
    appId: '1:861560885487:ios:c0e6b1ef7f917012a64b1a',
    messagingSenderId: '861560885487',
    projectId: 'letmecook-864e0',
    storageBucket: 'letmecook-864e0.appspot.com',
    iosBundleId: 'com.example.letmecook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Gixanp9Kf7k_T0o6HyESchnew7Nxqjs',
    appId: '1:861560885487:web:ea3fc42a4e2170c2a64b1a',
    messagingSenderId: '861560885487',
    projectId: 'letmecook-864e0',
    authDomain: 'letmecook-864e0.firebaseapp.com',
    storageBucket: 'letmecook-864e0.appspot.com',
    measurementId: 'G-NLKKYJ1ZL1',
  );
}
